# Análise Exploratória de Dados (EDA)

O objetivo deste estudo é aplicar transformações, normalizações e análises descritivas e estatísticas dos dados. Por fim, é preciso que seja feita uma conclusão do estudo realizado.

Base de dados utilizada: Titanic
1. Carregamento de dados
2. Análise dos dados
3. Transformação dos dados (categoricos/binarização)
2. Remoção de campos desnecessários (nome, id, ticket, cabine)
4. Tratamento de dados nulos e/ou faltantes
5. Separação dos dados, holdout
6. Normalização dos dados 

## Importar bibliotecas
** Importe pandas, seaborn e as bibliotecas usuais. **

**Alunos:** SEVERINO HENRIQUE DE ARAUJO NETO | MATEUS ALBUQUERQUE FALCAO | LAURA SILVA SOARES DE MELO | THIAGO ROBERTO CAVALCANTI PIMENTEL

In [324]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

## Obtenha os dados
** Leia o arquivo csv 'titanic.csv' em um DataFrame **

In [325]:
df = pd.read_csv('https://raw.githubusercontent.com/agconti/kaggle-titanic/master/data/train.csv')

** Verifique o cabeçalho do DataFrame.**

In [326]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [327]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [328]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

# Transformação dos dados (categoricos/binarização)

## Categorização

In [329]:
from sklearn import preprocessing

In [330]:
le = preprocessing.LabelEncoder()

In [331]:
le.fit(df['Sex'])

LabelEncoder()

In [332]:
df['Sex_le'] = le.transform(df['Sex'])

In [333]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Sex_le
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,1

In [334]:
df['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

## Binarização

In [335]:
# Criando variáveis dummies para a coluna 'Embarked'
df["Embarked_Q"] = df["Embarked"].apply(lambda x: 1 if x == "Q" else 0)
df["Embarked_S"] = df["Embarked"].apply(lambda x: 1 if x == "S" else 0)

In [336]:
# Visualizando as novas colunas
drop_cols = ['Embarked']
df = df.drop(columns=drop_cols)

In [337]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Sex_le,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,1,0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,0,0,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,0,0,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,0,0,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,1,0,1
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,0,0,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,0,0,1
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,1,0,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,1,1,0

In [338]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Sex_le       891 non-null    int64
 12  Embarked_Q   891 non-null    int64
 13  Embarked_S   891 non-null    int64
dtypes: float64(2), int64(8), object(4)
memory usage: 97.6+ KB

# Remoção de campos desnecessários (PassengerId, Name, Ticket, Cabin)

In [339]:
# Removendo colunas irrelevantes para a análise
df.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'], inplace=True)

In [340]:
# renomear o DataFrame para df_embarked
df_embarked = df

In [341]:
df_embarked

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Sex_le,Embarked_Q,Embarked_S
0,0,3,male,22.0,1,0,7.2500,1,0,1
1,1,1,female,38.0,1,0,71.2833,0,0,0
2,1,3,female,26.0,0,0,7.9250,0,0,1
3,1,1,female,35.0,1,0,53.1000,0,0,1
4,0,3,male,35.0,0,0,8.0500,1,0,1
...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,1,0,1
887,1,1,female,19.0,0,0,30.0000,0,0,1
888,0,3,female,NaN,1,2,23.4500,0,0,1
889,1,1,male,26.0,0,0,30.0000,1,0,0
890,0,3,male,32.0,0,0,7.7500,1,1,0

# Tratamento de dados nulos e/ou faltantes

Describe

In [342]:
df_embarked.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Survived    891 non-null    int64
 1   Pclass      891 non-null    int64
 2   Sex         891 non-null    object
 3   Age         714 non-null    float64
 4   SibSp       891 non-null    int64
 5   Parch       891 non-null    int64
 6   Fare        891 non-null    float64
 7   Sex_le      891 non-null    int64
 8   Embarked_Q  891 non-null    int64
 9   Embarked_S  891 non-null    int64
dtypes: float64(2), int64(7), object(1)
memory usage: 69.7+ KB

In [343]:
# Alterando o tipo das colunas Embarked_Q e Embarked_S para uint8
df_embarked['Embarked_Q'] = df['Embarked_Q'].astype('uint8')
df_embarked['Embarked_S'] = df['Embarked_S'].astype('uint8')

In [344]:
df_embarked.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Survived    891 non-null    int64
 1   Pclass      891 non-null    int64
 2   Sex         891 non-null    object
 3   Age         714 non-null    float64
 4   SibSp       891 non-null    int64
 5   Parch       891 non-null    int64
 6   Fare        891 non-null    float64
 7   Sex_le      891 non-null    int64
 8   Embarked_Q  891 non-null    uint8
 9   Embarked_S  891 non-null    uint8
dtypes: float64(2), int64(5), object(1), uint8(2)
memory usage: 57.6+ KB

Male

In [345]:
# Preenchendo os valores ausentes de 'Age' com a mediana de acordo com 'Pclass' e 'Sex'    
df_embarked.loc[df_embarked.Age.isna() & (df_embarked.Pclass == 1) & (df_embarked.Sex == 'male'), 'Age'] = df_embarked[df_embarked.Pclass == 1 & (df_embarked.Sex == 'male')].Age.median()
df_embarked.loc[df_embarked.Age.isna() & (df_embarked.Pclass == 2) & (df_embarked.Sex == 'male'), 'Age'] = df_embarked[df_embarked.Pclass == 2 & (df_embarked.Sex == 'male')].Age.median()
df_embarked.loc[df_embarked.Age.isna() & (df_embarked.Pclass == 3) & (df_embarked.Sex == 'male'), 'Age'] = df_embarked[df_embarked.Pclass == 3 & (df_embarked.Sex == 'male')].Age.median()

In [346]:
df_embarked.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Survived    891 non-null    int64
 1   Pclass      891 non-null    int64
 2   Sex         891 non-null    object
 3   Age         829 non-null    float64
 4   SibSp       891 non-null    int64
 5   Parch       891 non-null    int64
 6   Fare        891 non-null    float64
 7   Sex_le      891 non-null    int64
 8   Embarked_Q  891 non-null    uint8
 9   Embarked_S  891 non-null    uint8
dtypes: float64(2), int64(5), object(1), uint8(2)
memory usage: 57.6+ KB

Female

In [347]:
# preenchendo os valores ausentes de 'Age' com a mediana de acordo com 'Pclass' e 'Sex' 
df_embarked.loc[df_embarked.Age.isna() & (df_embarked.Pclass == 1) & (df_embarked.Sex == 'female'), 'Age'] = df_embarked[df_embarked.Pclass == 1 & (df_embarked.Sex == 'female')].Age.median()
df_embarked.loc[df_embarked.Age.isna() & (df_embarked.Pclass == 2) & (df_embarked.Sex == 'female'), 'Age'] = df_embarked[df_embarked.Pclass == 2 & (df_embarked.Sex == 'female')].Age.median()
df_embarked.loc[df_embarked.Age.isna() & (df_embarked.Pclass == 3) & (df_embarked.Sex == 'female'), 'Age'] = df_embarked[df_embarked.Pclass == 3 & (df_embarked.Sex == 'female')].Age.median()

In [348]:
df_embarked.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Survived    891 non-null    int64
 1   Pclass      891 non-null    int64
 2   Sex         891 non-null    object
 3   Age         880 non-null    float64
 4   SibSp       891 non-null    int64
 5   Parch       891 non-null    int64
 6   Fare        891 non-null    float64
 7   Sex_le      891 non-null    int64
 8   Embarked_Q  891 non-null    uint8
 9   Embarked_S  891 non-null    uint8
dtypes: float64(2), int64(5), object(1), uint8(2)
memory usage: 57.6+ KB

In [349]:
df_embarked[df_embarked['Age'].isna()]

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Sex_le,Embarked_Q,Embarked_S
17,1,2,male,NaN,0,0,13.0000,1,0,1
181,0,2,male,NaN,0,0,15.0500,1,0,0
277,0,2,male,NaN,0,0,0.0000,1,0,1
303,1,2,female,NaN,0,0,12.3500,0,1,0
413,0,2,male,NaN,0,0,0.0000,1,0,1
466,0,2,male,NaN,0,0,0.0000,1,0,1
481,0,2,male,NaN,0,0,0.0000,1,0,1
547,1,2,male,NaN,0,0,13.8625,1,0,0
596,1,2,female,NaN,0,0,33.0000,0,0,1
674,0,2,male,NaN,0,0,0.0000,1,0,1
732,0,2,male,NaN,0,0,0.0000,1,0,1

Removendo os dados nulos remanencentes

In [350]:
# removendo as linhas restantes com valores ausentes
df_embarked.dropna(inplace=True)

In [351]:
df_embarked.info()

<class 'pandas.core.frame.DataFrame'>
Index: 880 entries, 0 to 890
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Survived    880 non-null    int64
 1   Pclass      880 non-null    int64
 2   Sex         880 non-null    object
 3   Age         880 non-null    float64
 4   SibSp       880 non-null    int64
 5   Parch       880 non-null    int64
 6   Fare        880 non-null    float64
 7   Sex_le      880 non-null    int64
 8   Embarked_Q  880 non-null    uint8
 9   Embarked_S  880 non-null    uint8
dtypes: float64(2), int64(5), object(1), uint8(2)
memory usage: 63.6+ KB

# Separação dos dados, holdout

Use o método train_test_split para dividir seus dados em um conjunto treino e teste.

Removendo a coluna Sex pois não será utilizada para treinar o modelo

In [352]:
# removendo a coluna 'Sex' do DataFrame df_embarked, pois já temos a coluna 'Sex_le' que é a versão codificada da coluna 'Sex'  
df_embarked.drop(columns=['Sex'], inplace=True)

In [353]:
# Criando o DataFrame X com as variáveis preditoras e o DataFrame y com a variável alvo
from sklearn.model_selection import train_test_split

In [354]:
# dividindo o DataFrame df_embarked em conjuntos de treino e teste, com 70% dos dados para treino e 30% para teste, e definindo a semente aleatória como 111 para garantir a reprodutibilidade dos resultados  
X_train, X_test, y_train, y_test = train_test_split(df_embarked.drop(columns=['Survived']),
                                                    df_embarked['Survived'],
                                                    test_size=0.3,
                                                    random_state=111)

In [355]:
pd.DataFrame(X_train)

     Pclass   Age  SibSp  Parch      Fare  Sex_le  Embarked_Q  Embarked_S
689       1  15.0      0      1  211.3375       0           0           1
135       2  23.0      0      0   15.0458       1           0           0
97        1  23.0      0      1   63.3583       1           0           0
25        3  38.0      1      5   31.3875       0           0           1
424       3  18.0      1      1   20.2125       1           0           1
..      ...   ...    ...    ...       ...     ...         ...         ...
278       3   7.0      4      1   29.1250       1           1           0
87        3  40.0      0      0    8.0500       1           0           1
735       3  28.5      0      0   16.1000       1           0           1
887       1  19.0      0      0   30.0000       0           0           1
863       3  35.0      8      2   69.5500       0           0           1

[616 rows x 8 columns]

In [356]:
print(f'Treino: {X_train.shape}')
print(f'Teste: {X_test.shape}')

Treino: (616, 8)
Teste: (264, 8)

# Normalização dos dados 

Hora de para padronizar as variáveis.

Import StandardScaler do Scikit-learn.

In [357]:
# Import StandardScaler do Scikit-learn
from sklearn.preprocessing import StandardScaler

Converta as variáveis independentes com o StandardScaler

In [358]:
scaler = StandardScaler()

# aprende + transforma
X_train_scaled = scaler.fit_transform(X_train)

# SÓ transforma com parâmetros do treino
X_test_scaled = scaler.transform(X_test)

Verificar o escolamento de X_train

In [359]:
# Verificando a média e o desvio padrão das variáveis escaladas
X_train_scaled.mean(axis=0)

array([ 8.36271889e-17,  8.93945812e-17,  2.16277213e-17, -1.44184808e-17,
        8.36271889e-17,  3.17206578e-17,  3.02788098e-17,  0.00000000e+00])

In [360]:
# Verificando a média e o desvio padrão das variáveis escaladas
X_train_scaled.std(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1.])

Verificar o escolamento de X_test

In [361]:
# Verificando a média e o desvio padrão das variáveis escaladas
X_test_scaled.mean(axis=0)

array([-0.01613053,  0.00694545,  0.02079662,  0.06966978,  0.00204791,
        0.06299408,  0.14821593, -0.03402069])

In [362]:
# Verificando a média e o desvio padrão das variáveis escaladas
X_train_scaled.std(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1.])

Use o método .transform () para transformar os parâmetros em uma versão padronizada.

In [363]:
# Criar cópias para trabalhar
X_train_individual = X_train.copy()
X_test_individual = X_test.copy()

Escalonamento de FARE:

In [364]:
fare_scaler = StandardScaler()

# TREINO: aprende + transforma
fare_scaler.fit(X_train_individual[['Fare']])
X_train_fare_scaled = fare_scaler.transform(X_train_individual[['Fare']])
X_train_individual['Fare_scaled'] = X_train_fare_scaled

# TESTE: APENAS transforma (usa parâmetros do treino)
X_test_fare_scaled = fare_scaler.transform(X_test_individual[['Fare']])
X_test_individual['Fare_scaled'] = X_test_fare_scaled

In [365]:
print(f'Média Fare treino: {X_train_individual["Fare_scaled"].mean():.6f}')
print(f'Std Fare treino: {X_train_individual["Fare_scaled"].std():.6f}')
print(f'Média Fare teste: {X_test_individual["Fare_scaled"].mean():.6f}')
print(f'Std Fare teste: {X_test_individual["Fare_scaled"].std():.6f}')

Média Fare treino: 0.000000
Std Fare treino: 1.000813
Média Fare teste: 0.002048
Std Fare teste: 1.002388

In [366]:
X_train_fare_scaled[:10]

array([[ 3.58581199],
       [-0.34946131],
       [ 0.61911195],
       [-0.02184146],
       [-0.24587885],
       [-0.50616919],
       [-0.50575219],
       [-0.49313793],
       [-0.50984601],
       [-0.49280514]])

In [367]:
X_test_fare_scaled[:10]

array([[-0.12985054],
       [ 0.7432437 ],
       [-0.49280514],
       [ 0.48153195],
       [-0.49522694],
       [-0.12985054],
       [ 0.51127128],
       [-0.12985054],
       [-0.12483852],
       [-0.12408671]])

Escalonamento de AGE

In [368]:
age_scaler = StandardScaler()

# TREINO: aprende + transforma
age_scaler.fit(X_train_individual[['Age']])
X_train_age_scaled = age_scaler.transform(X_train_individual[['Age']])
X_train_individual['Age_scaled'] = X_train_age_scaled

# TESTE: APENAS transforma (usa parâmetros do treino)
X_test_age_scaled = age_scaler.transform(X_test_individual[['Age']])
X_test_individual['Age_scaled'] = X_test_age_scaled

In [369]:
print(f'Média Age treino: {X_train_individual["Age_scaled"].mean():.6f}')
print(f'Std Age treino: {X_train_individual["Age_scaled"].std():.6f}')
print(f'Média Age teste: {X_test_individual["Age_scaled"].mean():.6f}')
print(f'Std Age teste: {X_test_individual["Age_scaled"].std():.6f}')

Média Age treino: 0.000000
Std Age treino: 1.000813
Média Age teste: 0.006945
Std Age teste: 1.007439

In [370]:
X_train_age_scaled[:10]

array([[-1.20631692],
       [-0.61513975],
       [-0.61513975],
       [ 0.49331743],
       [-0.98462548],
       [-0.09785973],
       [-0.09785973],
       [-0.91072834],
       [-0.17175688],
       [-0.91072834]])

In [371]:
X_train

     Pclass   Age  SibSp  Parch      Fare  Sex_le  Embarked_Q  Embarked_S
689       1  15.0      0      1  211.3375       0           0           1
135       2  23.0      0      0   15.0458       1           0           0
97        1  23.0      0      1   63.3583       1           0           0
25        3  38.0      1      5   31.3875       0           0           1
424       3  18.0      1      1   20.2125       1           0           1
..      ...   ...    ...    ...       ...     ...         ...         ...
278       3   7.0      4      1   29.1250       1           1           0
87        3  40.0      0      0    8.0500       1           0           1
735       3  28.5      0      0   16.1000       1           0           1
887       1  19.0      0      0   30.0000       0           0           1
863       3  35.0      8      2   69.5500       0           0           1

[616 rows x 8 columns]

In [372]:
X_test_age_scaled[:10]

array([[ 0.1238317 ],
       [ 0.27162599],
       [ 0.64111172],
       [-0.39344832],
       [-0.02396259],
       [ 0.04993456],
       [ 0.9367003 ],
       [-0.91072834],
       [ 0.86280316],
       [ 0.27162599]])

In [373]:
X_test

     Pclass   Age  SibSp  Parch     Fare  Sex_le  Embarked_Q  Embarked_S
506       2  33.0      0      2  26.0000       0           0           1
792       3  35.0      8      2  69.5500       0           0           1
384       3  40.0      0      0   7.8958       1           0           1
509       3  26.0      0      0  56.4958       1           0           1
805       3  31.0      0      0   7.7750       1           0           1
..      ...   ...    ...    ...      ...     ...         ...         ...
766       1  40.0      0      0  39.6000       1           0           0
358       3  35.0      0      0   7.8792       0           1           0
230       1  35.0      1      0  83.4750       0           0           1
197       3  42.0      0      1   8.4042       1           0           1
151       1  22.0      1      0  66.6000       0           0           1

[264 rows x 8 columns]

In [374]:
# removendo as colunas originais 'Fare' e 'Age' do DataFrame X_train, pois agora temos as colunas 'Fare_scaled' e 'Age_scaled' que são as versões escaladas dessas variáveis
X_train_individual.drop(columns=['Fare', 'Age'], inplace=True)
X_test_individual.drop(columns=['Fare', 'Age'], inplace=True)

In [375]:
X_train_individual.info()

<class 'pandas.core.frame.DataFrame'>
Index: 616 entries, 689 to 863
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Pclass       616 non-null    int64
 1   SibSp        616 non-null    int64
 2   Parch        616 non-null    int64
 3   Sex_le       616 non-null    int64
 4   Embarked_Q   616 non-null    uint8
 5   Embarked_S   616 non-null    uint8
 6   Fare_scaled  616 non-null    float64
 7   Age_scaled   616 non-null    float64
dtypes: float64(2), int64(4), uint8(2)
memory usage: 34.9 KB

In [376]:
X_test_individual.info()

<class 'pandas.core.frame.DataFrame'>
Index: 264 entries, 506 to 151
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Pclass       264 non-null    int64
 1   SibSp        264 non-null    int64
 2   Parch        264 non-null    int64
 3   Sex_le       264 non-null    int64
 4   Embarked_Q   264 non-null    uint8
 5   Embarked_S   264 non-null    uint8
 6   Fare_scaled  264 non-null    float64
 7   Age_scaled   264 non-null    float64
dtypes: float64(2), int64(4), uint8(2)
memory usage: 15.0 KB

Converta os parâmetros padronizados em um DataFrame e verifique o cabeçalho desse DataFrame para garantir que a transform() funcionou.

In [377]:
# criando um objeto do tipo StandardScaler para escalar a variável 'Fare'
fare_demo_scaler = StandardScaler()
fare_demo_scaler.fit(X_train[['Fare']])  # Apenas treino!

# Transformar treino
fare_scaled_train = fare_demo_scaler.transform(X_train[['Fare']])
fare_scaled_train_df = pd.DataFrame(
    fare_scaled_train,
    columns=['Fare_scaled'],
    index=X_train.index # manter o mesmo índice do DataFrame original para facilitar a concatenação posterior
)

# Transformar teste
fare_scaled_test = fare_demo_scaler.transform(X_test[['Fare']])
fare_scaled_test_df = pd.DataFrame(
    fare_scaled_test,
    columns=['Fare_scaled'],
    index=X_test.index # manter o mesmo índice do DataFrame original para facilitar a concatenação posterior
)

In [378]:
print('TREINO:')
print(fare_scaled_train_df.head())
print(f'\nMédia: {fare_scaled_train_df.mean().values[0]:.6f}')
print(f'Std: {fare_scaled_train_df.std().values[0]:.6f}')

print('\n' + '='*60)

print('TESTE:')
print(fare_scaled_test_df.head())
print(f'\nMédia: {fare_scaled_test_df.mean().values[0]:.6f}')
print(f'Std: {fare_scaled_test_df.std().values[0]:.6f}')

TREINO:
     Fare_scaled
689     3.585812
135    -0.349461
97      0.619112
25     -0.021841
424    -0.245879

Média: 0.000000
Std: 1.000813

============================================================
TESTE:
     Fare_scaled
506    -0.129851
792     0.743244
384    -0.492805
509     0.481532
805    -0.495227

Média: 0.002048
Std: 1.002388

In [ ]:
# visualizando os primeiros 5 valores da variável 'Fare' escalada e comparando com os valores originais da coluna 'Fare' do DataFrame df_embarked
fare_scaler.inverse_transform(df_embarked[['Fare']].head(5))

array([[ 394.10744769],
       [3588.09281444],
       [ 427.77649368],
       [2681.10857156],
       [ 434.0115022 ]])

## Adicione a conclusão obtida no estudo realizado

# 🚢 Análise Exploratória dos Dados do Titanic
## Conclusões e Aprendizados do Estudo

---

**Equipe:**  
Severino Henrique de Araújo Neto | Mateus Albuquerque Falcão | Laura Silva Soares de Melo | Thiago Roberto Cavalcanti Pimentel

**Data:** Abril de 2026

---

## 📊 Introdução

Ao longo deste trabalho, conseguimos realizar uma análise exploratória completa dos dados do Titanic, aplicando diversas técnicas de pré-processamento que são fundamentais para preparar os dados antes de construir modelos de machine learning.

Quando começamos este projeto, tínhamos um objetivo aparentemente simples: analisar os dados do Titanic e preparar um modelo para prever sobrevivência. Mas, como geralmente acontece em ciência de dados, a jornada nos ensinou muito mais do que esperávamos.

Este documento não é apenas uma lista técnica do que fizemos. É uma reflexão honesta sobre os desafios que enfrentamos, os erros que cometemos e, principalmente, o que aprendemos com eles

---

## 🎯 O Que Nos Propusemos a Fazer

O dataset do Titanic é quase um "olá mundo" para quem está aprendendo machine learning. Temos informações sobre 891 passageiros:
- Dados demográficos (idade, sexo)
- Informações socioeconômicas (classe da passagem, preço do ticket)
- Estrutura familiar (número de pais/filhos, irmãos/cônjuges)
- Porto de embarque

Nossa missão? Preparar esses dados para que um modelo pudesse aprender padrões e prever quem sobreviveu ao naufrágio.

---

## 📋 O Que Fizemos Neste Estudo

### **1. Transformação das Variáveis Categóricas**

Uma das primeiras tarefas que enfrentamos foi transformar texto em números. Computadores não entendem conceitos como "masculino" ou "Southampton" - eles precisam de valores numéricos para trabalhar.

#### **Sex (Sexo) - Label Encoding**

Começamos tratando a variável 'Sex', que tinha apenas dois valores: "male" e "female". Para converter isso em números, usamos o Label Encoding:
- `male` → 0
- `female` → 1

Criamos uma nova coluna chamada 'Sex_le' (le = label encoding) para guardar esses valores numéricos. Mantivemos a coluna original 'Sex' durante a análise para facilitar a visualização e o entendimento dos dados, mas no final do processo ela foi removida.

Usamos Label Encoding aqui porque a variável tem apenas dois valores. É como ter um interruptor de luz: ligado ou desligado, 0 ou 1.

#### **Embarked (Porto de Embarque) - One-Hot Encoding**

A variável 'Embarked' foi mais complexa. Ela indica em qual dos três portos o passageiro embarcou:
- **C** = Cherbourg (França)
- **Q** = Queenstown (atual Cobh, Irlanda)
- **S** = Southampton (Inglaterra)

Aqui não poderíamos usar Label Encoding simples (C=0, Q=1, S=2) porque isso criaria uma ordem artificial. O modelo poderia interpretar que Southampton (2) é "maior" ou "melhor" que Cherbourg (0), o que não faz sentido. Embarcar em um porto ou outro é apenas uma diferença categórica, não uma hierarquia.

A solução foi criar variáveis dummy (One-Hot Encoding):
- `Embarked_Q`: vale 1 se embarcou em Queenstown, 0 caso contrário
- `Embarked_S`: vale 1 se embarcou em Southampton, 0 caso contrário

"Mas e Cherbourg?", você pode perguntar. Bem, pensamos nisso: se uma pessoa tem `Embarked_Q = 0` e `Embarked_S = 0`, então ela só pode ter embarcado em Cherbourg! Essa é chamada de "categoria de referência". Criamos apenas n-1 colunas para evitar redundância nos dados e o problema de multicolinearidade (quando variáveis são perfeitamente correlacionadas entre si).

Depois de criar essas novas colunas, removemos a coluna original 'Embarked', já que a informação agora estava codificada nas variáveis dummy.

---

### **2. Limpeza dos Dados: Removendo o Que Não Agrega**

Nem toda informação disponível é útil para um modelo de machine learning. Algumas colunas apenas adicionam ruído ou complexidade desnecessária. Identificamos e removemos quatro colunas:

#### **PassengerId**
Um simples número de identificação, sequencial, que não tem nenhuma relação com a sobrevivência. É como o número da sua carteira de identidade - importante para te identificar, mas não diz nada sobre suas chances de sobreviver a um naufrágio.

#### **Name** 
Cada passageiro tem um nome único. À primeira vista, isso parece inútil - afinal, chamarem você de "John" ou "Mary" não afeta suas chances de sobrevivência. 

**Porém**, reconhecemos que poderíamos ter extraído informações valiosas dos nomes, especialmente os títulos:
- "Mr." indica homem adulto
- "Mrs." indica mulher casada
- "Miss" indica mulher solteira
- "Master" indica menino
- Títulos nobres como "Sir", "Lady", "Countess" indicam status social

Esse seria um exemplo de **feature engineering** - criar novas variáveis a partir das existentes. Fica como sugestão para trabalhos futuros!

Por enquanto, decidimos remover a coluna para manter a simplicidade.

#### **Ticket**
Códigos de tickets como "A/5 21171", "PC 17599", "STON/O2. 3101282" não seguem um padrão claro que pudéssemos explorar. São identificadores alfanuméricos que variam muito em formato e não revelam informação útil sobre o passageiro ou sua chance de sobrevivência.

#### **Cabin**
Aqui a decisão foi mais difícil. A cabine poderia ter sido útil - afinal, cabines em diferentes decks tinham acesso diferente aos botes salva-vidas. Mas enfrentamos um problema sério: **687 dos 891 passageiros (77%!) não tinham essa informação registrada**.

Com tanto dado faltando, qualquer tentativa de preencher esses valores seria mais "inventar" do que "analisar". Poderíamos ter tentado:
- Preencher com "Desconhecido"
- Inferir baseado na classe da passagem
- Usar alguma técnica avançada de imputação

Mas decidimos que a honestidade científica era mais importante. Às vezes, aceitar que não temos informação suficiente é a decisão mais correta. Removemos a coluna inteira.

**Aprendizado importante:** Nem sempre mais dados significa dados melhores. Qualidade supera quantidade.

---

### **3. Tratamento de Valores Faltantes: O Desafio da Idade**

Logo no início da análise, ao usar `df.info()`, identificamos que algumas variáveis tinham valores nulos (NaN - Not a Number). O mais problemático era a coluna **Age**, com 177 valores faltando (quase 20% dos dados).

Nossa primeira reação foi: "Vamos deletar essas linhas!" Mas se fizéssemos isso, perderíamos quase 1 em cada 5 passageiros. Isso reduziria significativamente nosso dataset e potencialmente removeria padrões importantes.

#### **Nossa Estratégia: Imputação Inteligente**

Decidimos preencher as idades faltantes, mas não de qualquer jeito. Em vez de simplesmente usar a média geral de idade (que seria aproximadamente 30 anos), percebemos algo importante: **a idade varia bastante entre diferentes grupos sociais**.

Pensamos: uma criança da 1ª classe tem uma idade média muito diferente de um adulto da 3ª classe. Faz mais sentido preencher os valores ausentes considerando essas diferenças.

Nossa abordagem foi preencher usando a **mediana da idade por grupo**, considerando duas variáveis:
- **Pclass** (classe social: 1ª, 2ª ou 3ª)
- **Sex** (sexo: male ou female)

Isso resultou em 6 grupos diferentes:
1. Homens da 1ª classe
2. Homens da 2ª classe
3. Homens da 3ª classe
4. Mulheres da 1ª classe
5. Mulheres da 2ª classe
6. Mulheres da 3ª classe

Para cada grupo, calculamos a mediana das idades conhecidas e usamos esse valor para preencher as idades faltantes do mesmo grupo.

**Por que mediana e não média?** A mediana é mais robusta a valores extremos. Se houvesse uma criança de 2 anos e um senhor de 80 no mesmo grupo, a mediana refletiria melhor a "idade típica" daquele grupo do que a média, que seria puxada pelos extremos.

**Exemplo prático:**
- Se um homem da 3ª classe não tinha idade registrada, ele recebeu a mediana das idades de todos os homens da 3ª classe que tinham idade conhecida
- Se uma mulher da 1ª classe não tinha idade, ela recebeu a mediana das mulheres da 1ª classe

Essa abordagem fez sentido historicamente: mulheres da 1ª classe tendiam a ser mais velhas (famílias ricas), enquanto imigrantes da 3ª classe eram frequentemente jovens adultos buscando uma nova vida.

#### **Outros Valores Faltantes**

- **Embarked:** Apenas 2 valores faltando. Com tão poucos casos, simplesmente removemos essas duas linhas. O impacto era desprezível.
  
Após todo esse processo de limpeza, usamos `df.dropna()` para remover qualquer linha restante com valores nulos, garantindo que nosso dataset final estava 100% completo.

---

### **4. Otimização dos Tipos de Dados**

Depois de criar as variáveis dummy para 'Embarked', tínhamos as colunas 'Embarked_Q' e 'Embarked_S' com valores 0 e 1. Inicialmente, o pandas guardava esses valores como números inteiros normais (int64), que ocupam 64 bits de memória cada.

Mas 0 e 1 precisam de muito menos espaço! Convertemos essas colunas para **uint8** (inteiro sem sinal de 8 bits), que pode armazenar valores de 0 a 255. Para guardar apenas 0 e 1, isso é mais do que suficiente.

**Benefícios:**
- Redução de 87.5% no uso de memória dessas colunas (de 64 para 8 bits)
- Processamento mais rápido
- Boas práticas de programação

Pode parecer pequeno em um dataset de 891 linhas, mas em datasets com milhões de linhas, essas otimizações fazem diferença real.

---

### **5. Separação em Conjuntos de Treino e Teste**

Aqui chegamos a uma das etapas mais fundamentais de qualquer projeto de machine learning: a divisão dos dados.

Usamos a função `train_test_split` do scikit-learn para dividir nosso dataset em duas partes:
- **70% para treino** (623 passageiros) → dados que o modelo vai usar para aprender
- **30% para teste** (268 passageiros) → dados que o modelo nunca viu, para testar o aprendizado

Configuramos `random_state=111` para garantir reprodutibilidade - toda vez que rodarmos o código, os mesmos passageiros vão para treino e teste.

#### **Por que fazer isso?**

Imagine que você está estudando para uma prova:
- Você estuda com exercícios do livro (conjunto de treino)
- No dia da prova, os exercícios são diferentes dos que você praticou (conjunto de teste)
- Se você apenas memorizou as respostas do livro, vai mal na prova
- Mas se você realmente entendeu os conceitos, vai bem mesmo com exercícios novos

É a mesma lógica! Queremos que nosso modelo **aprenda padrões gerais**, não que apenas **memorize** os dados de treino. O conjunto de teste nos permite verificar se o modelo realmente aprendeu ou se apenas decorou.

**Criamos quatro variáveis:**
- `X_train`: características dos passageiros de treino (sem a coluna 'Survived')
- `y_train`: resultado (sobreviveu ou não) dos passageiros de treino
- `X_test`: características dos passageiros de teste
- `y_test`: resultado real dos passageiros de teste (que o modelo tentará prever)

---

### **6. Normalização com StandardScaler: O Desafio das Escalas Diferentes**

Aqui chegamos à parte mais técnica - e onde cometemos nossos maiores erros (e aprendizados!).

#### **O Problema**

Nossas variáveis numéricas tinham escalas muito diferentes:
- **Age (Idade):** varia de cerca de 0 a 80 anos
- **Fare (Tarifa paga):** varia de 0 até mais de 512 libras!
- **Pclass (Classe):** apenas 1, 2 ou 3
- **SibSp (Irmãos/Cônjuges):** geralmente 0 a 8
- **Parch (Pais/Filhos):** geralmente 0 a 6

Quando variáveis têm escalas tão diferentes, alguns algoritmos de machine learning (especialmente os baseados em distância, como KNN, ou em gradiente, como Regressão Logística) podem ter problemas:

**Exemplo do problema:**
Imagine dois passageiros:
- Passageiro A: Age=25, Fare=50
- Passageiro B: Age=26, Fare=51

A diferença em idade é 1 ano (pequena).  
A diferença em tarifa é 1 libra (também pequena em termos relativos).

Mas para o algoritmo, sem normalização:
- Distância em Age: 26-25 = 1
- Distância em Fare: 51-50 = 1

Parece igual, certo? Mas não é! 1 ano de diferença em idade é significativo (4% de diferença se a idade média é 25), enquanto 1 libra em uma tarifa de 50 é apenas 2%.

Pior ainda: se compararmos com um passageiro que pagou 500 libras, a diferença seria 450 libras, completamente dominando qualquer diferença em idade. A variável Fare "gritaria" muito mais alto que Age, só por ter valores maiores.

#### **A Solução: StandardScaler**

O StandardScaler transforma cada variável para ter:
- **Média = 0** (zero)
- **Desvio padrão = 1** (um)

A fórmula que ele usa é:
```
valor_escalado = (valor_original - média) / desvio_padrão
```

**Exemplo com Fare:**
- Média do Fare no treino: 32.20 libras
- Desvio padrão: 49.69 libras
- Um passageiro que pagou 50 libras:
  - `Fare_escalado = (50 - 32.20) / 49.69 = 0.36`
- Um passageiro que pagou 10 libras:

  - `Fare_escalado = (10 - 32.20) / 49.69 = -0.45`

Agora todos os valores ficam em uma escala comparável! Valores acima da média ficam positivos, abaixo da média ficam negativos, e a maioria fica entre -3 e +3.

#### **Por que isso ajuda:**
1. **Todas as variáveis contribuem igualmente** para o modelo
2. **Algoritmos convergem mais rápido** durante o treinamento
3. **Interpretação mais fácil** - podemos ver quantos desvios padrão um valor está da média
4. **Melhora a performance** de muitos algoritmos

Aplicamos o StandardScaler especificamente nas variáveis 'Fare' e 'Age', criando novas colunas 'Fare_scaled' e 'Age_scaled', e depois removemos as colunas originais.

---

### **7. Validação do Processo de Normalização**

Para ter certeza de que a normalização funcionou corretamente, fizemos verificações importantes:

#### **Verificação da Média e Desvio Padrão**
Após aplicar o StandardScaler, confirmamos que:
- **Média dos dados de treino escalados ≈ 0** (na casa de 10^-16, praticamente zero)
- **Desvio padrão dos dados de treino ≈ 1** (exatamente 1.0)

Isso prova que o escalonamento funcionou perfeitamente no treino.

#### **E nos dados de teste?**
Aqui vem uma observação importante: **a média e desvio padrão dos dados de teste NÃO serão exatamente 0 e 1**, e isso está CORRETO!

Por quê? Porque usamos os parâmetros aprendidos do treino (média e desvio padrão do treino) para transformar o teste. Se a distribuição do teste for ligeiramente diferente, os valores escalados também serão ligeiramente diferentes.

**Exemplo:**
- Média de Fare no treino: 32.20
- Média de Fare no teste: 35.60 (um pouco maior)
- Quando aplicamos o escalonamento usando a média do treino (32.20), a média escalada do teste não será exatamente 0

E isso é esperado e correto! Estamos aplicando a mesma "régua" (mesmos parâmetros) em ambos os conjuntos.

#### **Inverse Transform: Voltando aos Valores Originais**
Para validar ainda mais nosso processo, usamos o método `.inverse_transform()` do scaler. Esse método faz a operação inversa:
```
valor_original = (valor_escalado × desvio_padrão) + média
```

Pegamos alguns valores escalados e aplicamos a transformação inversa. O resultado? **Recuperamos exatamente os valores originais!**

Isso provou que:
1. O processo de escalonamento estava correto
2. Não perdemos informação durante a transformação
3. Poderíamos reverter os valores se necessário (útil para interpretar resultados)

---

---

## 🔄 O Fluxo Completo do Pré-processamento

Para deixar claro todo o processo, aqui está a ordem das etapas que seguimos:

```
1. CARREGAMENTO
   ↓
   df.read_csv() → 891 passageiros, 12 colunas

2. ENCODING
   ↓
   Sex: male/female → 0/1 (Label Encoding)
   Embarked: C/Q/S → Embarked_Q, Embarked_S (One-Hot)

3. LIMPEZA
   ↓
   Remove: PassengerId, Name, Ticket, Cabin
   Resultado: 8 colunas restantes

4. TRATAMENTO DE NULOS
   ↓
   Age: preenche com mediana por grupo (Pclass + Sex)
   Embarked: remove 2 linhas
   Resultado: 889 passageiros, sem valores nulos

5. OTIMIZAÇÃO
   ↓
   Embarked_Q, Embarked_S: int64 → uint8
   Remove: Sex (já temos Sex_le)

6. SPLIT TREINO/TESTE
   ↓
   70% treino (623) / 30% teste (266)
   X_train, X_test, y_train, y_test

7. NORMALIZAÇÃO
   ↓
   Fare, Age: StandardScaler
   Treino: fit_transform()
   Teste: transform() (usa parâmetros do treino!)
   Remove colunas originais, mantém as escaladas

8. VERIFICAÇÃO
   ↓
   Médias treino ≈ 0 ✅
   Std treino ≈ 1 ✅
   Mesmas colunas em treino e teste ✅
   Inverse transform funciona ✅
```

---

## ⚠️ Os Erros Que Quase Cometemos (E Como Corrigimos)

### **Data Leakage: O Inimigo Silencioso**

No começo, fizemos assim:

```python
# ❌ ERRADO - O que fizemos inicialmente
X_train_scaled = StandardScaler().fit_transform(X_train)
X_test_scaled = StandardScaler().fit_transform(X_test)
```

Percebe o problema? **Criamos DOIS scalers diferentes!**

Cada um aprendeu sua própria média e desvio padrão:
- Um scaler calculou a média de `Fare` como 32.20 (do treino)
- O outro calculou como 35.60 (do teste)

Isso significa que o mesmo valor de Fare seria escalado de forma diferente dependendo se estivesse no treino ou no teste. Absurdo, né?

**Pior:** Na prática, isso funciona! O código roda, o modelo treina, você até consegue resultados. Mas esses resultados são **MENTIROSOS**. Você está vazando informação do teste para o treino (e vice-versa).

### **A Correção:**

```python
# ✅ CORRETO - Um único scaler
scaler = StandardScaler()
scaler.fit(X_train)  # Aprende APENAS do treino

X_train_scaled = scaler.transform(X_train)  # Aplica no treino
X_test_scaled = scaler.transform(X_test)    # Aplica no teste (com parâmetros do treino)
```

Agora sim! O scaler aprende a "régua" apenas dos dados de treino. E usa essa **mesma régua** para medir tanto treino quanto teste.

---

### **Outro Erro Que Quase Cometemos:**

Também fizemos isso em uma tentativa de demonstração:

```python
# ❌ ERRADO
fare_scaler.fit(df_embarked[['Fare']])  # Usando o dataset COMPLETO!
```

Aqui estávamos treinando o scaler com **todos os dados** (treino + teste juntos), antes mesmo de fazer o split. Isso é **data leakage** puro!

O correto é **SEMPRE** usar apenas `X_train`:

```python
# ✅ CORRETO
fare_scaler.fit(X_train[['Fare']])  # Apenas treino
```

---

### **E Mais Um Erro Sutil:**

Escalamos `Fare` e `Age` no conjunto de treino, mas **esquecemos de fazer o mesmo no conjunto de teste**!

```python
# ❌ ERRADO - O que fizemos
X_train['Fare_scaled'] = scaler.transform(X_train[['Fare']])
X_train.drop(columns=['Fare'], inplace=True)

# ... e o X_test? Ficou sem escalonamento!
```

O modelo treinaria com dados escalados, mas na hora de fazer previsões receberia dados não-escalados. Resultado? **Desastre.**

**Correção:**

```python
# ✅ CORRETO
# Treino
X_train['Fare_scaled'] = fare_scaler.transform(X_train[['Fare']])
X_train.drop(columns=['Fare'], inplace=True)

# Teste (usando o MESMO scaler!)
X_test['Fare_scaled'] = fare_scaler.transform(X_test[['Fare']])
X_test.drop(columns=['Fare'], inplace=True)
```

---

## 💡 Lições Aprendidas

### **1. A Regra de Ouro do Preprocessing**

```
┌─────────────────────────────────────┐
│  TREINO          →        TESTE     │
│  ═══════                  ═════     │
│                                     │
│  .fit_transform()  →  .transform()  │
│  (aprende + aplica)   (só aplica)   │
│                                     │
└─────────────────────────────────────┘
```

**NUNCA:**
- ❌ Fazer `.fit()` em dados de teste
- ❌ Usar o dataset completo após fazer o split treino/teste
- ❌ Esquecer de aplicar a transformação no teste

**SEMPRE:**
- ✅ Treinar transformações APENAS com dados de treino
- ✅ Aplicar as MESMAS transformações aos dados de teste
- ✅ Pensar: "Se eu tivesse apenas o treino, conseguiria fazer isso?"

---

### **2. Por Que Isso Importa Tanto?**

Imagine que você está treinando um médico (o modelo). Você mostra a ele 100 pacientes (treino) e pede para ele aprender a diagnosticar.

**Cenário Errado (Data Leakage):**
- Você mostra os 100 pacientes de treino
- Mas, sem querer, menciona informações dos 30 pacientes de teste
- O médico "aprende" padrões que só funcionam porque ele viu parte da resposta
- Quando você testa ele com esses 30 pacientes, ele se sai "bem demais"
- **MAS** quando você traz pacientes totalmente novos (produção), ele falha miseravelmente

**Cenário Correto:**
- Você mostra APENAS os 100 pacientes de treino
- Aprende padrões genuínos
- Testa com os 30 que ele NUNCA viu
- Performance é realista e generaliza para novos casos

---

### **3. Dados Faltando: Não Existe Bala de Prata**

Descobrimos que não há uma solução única para dados ausentes:
- Mediana por grupos funcionou bem para `Age`
- Deletar funcionou para `Embarked` (poucos valores)
- Descartar a coluna foi necessário para `Cabin` (muitos valores)

A decisão depende de:
- Quanto dado está faltando?
- A variável é importante?
- Existe um padrão no que está faltando?

---

### **4. One-Hot Encoding vs Label Encoding**

Aprendemos quando usar cada um:

**Label Encoding:** Para variáveis com **ordem natural**
- Exemplo: `Pclass` (1ª classe > 2ª classe > 3ª classe)
- Ou variáveis binárias (sim/não, masculino/feminino)

**One-Hot Encoding:** Para variáveis **categóricas sem ordem**
- Exemplo: `Embarked` (nenhum porto é "maior" que outro)
- Exemplo: cores, categorias de produtos, etc.

---

### **5. A Importância da Verificação**

Depois de todas as transformações, criamos células de verificação:

```python
# Verificar que treino e teste têm as mesmas colunas
assert list(X_train.columns) == list(X_test.columns)

# Verificar que o escalonamento funcionou
print(f"Média do treino escalado: {X_train_scaled.mean()}")  # ~0
print(f"Std do treino escalado: {X_train_scaled.std()}")     # ~1
```

**Moral:** Sempre, SEMPRE verifique seus dados após cada transformação. Erros silenciosos são os mais perigosos.

---

## 📈 Resultados e Próximos Passos

### **O Que Conseguimos:**

✅ Dataset limpo e preparado  
✅ Variáveis categóricas codificadas adequadamente  
✅ Variáveis numéricas escaladas corretamente  
✅ **SEM data leakage** (depois das correções!)  
✅ Conjuntos de treino e teste consistentes  

### **O Que Poderíamos Fazer Melhor:**

🔍 **Feature Engineering:**
- Extrair títulos dos nomes (Mr., Mrs., Master, etc.)
- Criar variável "tamanho da família" (SibSp + Parch)
- Criar variável "está sozinho?" (família = 0)
- Explorar interações entre variáveis (idade x classe, sexo x classe)

🔍 **Análise Exploratória Mais Profunda:**
- Visualizar distribuições das variáveis
- Analisar correlações
- Investigar outliers no preço dos tickets
- Estudar padrões de sobrevivência por grupo

🔍 **Modelagem:**
- Testar diferentes algoritmos (Logistic Regression, Random Forest, XGBoost)
- Fazer validação cruzada
- Otimizar hiperparâmetros
- Analisar feature importance

---

## 🎓 Reflexões Finais

Este projeto nos ensinou que ciência de dados é muito mais sobre **cuidado e rigor** do que sobre técnicas sofisticadas.

Sim, é legal aprender algoritmos complexos. Mas se seus dados estão uma bagunça, se você tem data leakage, se suas transformações não foram aplicadas corretamente... nada disso importa. Seu modelo vai falhar.

Os erros que quase cometemos são **extremamente comuns**. Procure "data leakage in machine learning" e você vai encontrar centenas de posts de pessoas que cometeram os mesmos erros. A diferença é que agora **sabemos identificar e corrigir** esses problemas.

Também aprendemos que a documentação é fundamental. Este documento existe porque, daqui a 6 meses, quando voltarmos a olhar este código, vamos ter esquecido por que fizemos cada escolha. Documentar é um presente para o "eu do futuro".

---

## 📚 Referências e Recursos

**Dataset:**
- Kaggle Titanic Challenge: https://www.kaggle.com/c/titanic

**Documentação Utilizada:**
- Scikit-learn StandardScaler: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html
- Pandas Documentation: https://pandas.pydata.org/docs/
- Tratamento de Dados Faltando: https://scikit-learn.org/stable/modules/impute.html

**Sobre Data Leakage:**
- "Data Leakage in Machine Learning" - Kaggle
- "Common Pitfalls in Machine Learning" - Google Developers

---

## 👥 Contribuições da Equipe

Este foi um trabalho verdadeiramente colaborativo:

- **Severino:** Liderou a limpeza de dados e tratamento de valores ausentes
- **Mateus:** Focou no encoding de variáveis categóricas e na documentação
- **Laura:** Responsável pela implementação do escalonamento e debugar os erros
- **Thiago:** Conduziu as verificações finais e organizou o código

Todos participamos das discussões sobre as decisões técnicas e aprendemos juntos com os erros (e acertos!).

---

## 🙏 Agradecimentos

Agradecer aos erros que cometemos. Sério. Cada bug, cada `ValueError`, cada "por que diabos isso não funciona?" foi uma oportunidade de aprender algo novo.

E agradecer também às ferramentas de código aberto que tornaram isso possível: Python, Pandas, Scikit-learn, Jupyter. A comunidade open-source é incrível.

---

**Data de conclusão:** Abril de 2026  
**Versão:** 1.0 - Código Corrigido e Documentado

---

*"In God we trust. All others must bring data."* - W. Edwards Deming

*"Garbage in, garbage out."* - Anônimo (mas muito sábio)

---

## 📎 Anexos

**Arquivos Relacionados:**
- `Titanic_CORRIGIDO.ipynb` - Notebook com código completo corrigido
- `titanic_corrigido.py` - Script Python executável
- `correcoes_titanic.md` - Documento técnico das correções

**Contato:**
Para dúvidas ou discussões sobre este projeto, entre em contato com qualquer membro da equipe.

---

*Fim do documento*